# Generated by Django 5.1.3 on 2024-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="cipher_text",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="vote",
            name="exponent",
            field=models.CharField(max_length=5000),
        ),
    ]
